/*
 * generated by Xtext
 */
package org.xtext;

import org.xtext.generator.ModuleDslGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ModuleDslRuntimeModule extends org.xtext.AbstractModuleDslRuntimeModule {

}
